version: '3.8'
services:
  api:
    build:
      context: /home/admin/ValheimControl
      dockerfile: docker/Dockerfile.back
    container_name: valheimcontrol_api
    restart: unless-stopped
    environment:
      # Bases de données hébergées sur l'hôte
      # DATABASE_URL: "mysql://user:password@185.158.107.98:3306/zooarcadia_db"
      # Si besoin de MongoDB, décommente et ajuste
      MONGODB_URL: "mongodb://user:password@185.158.107.98:27017/valheimcontrol_mongo"
    volumes:
      - ../backend_valheim_control:/var/www/api:ro
    networks:
      - valheimcontrol_net
    expose:
      - "8001"

  front:
    build:
      context: /home/admin/ValheimControl
      dockerfile: docker/Dockerfile.front
    container_name: valheimcontrol_front
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - valheimcontrol_net

networks:
  valheimcontrol_net:
    driver: bridge
